### ISSUE TITLE
titlelinks.txt | can auto delete tracking codes? [Starlink review: dreams, not reality - The Verge](https://www.theverge.com/22435030/starlink-satellite-internet-spacex-review?scrolla=5eb6d68b7fedc32c19ef33b4)

### ISSUE THREAD

**Issue by djinna** [vgururao/yakcollective#101]
eg
https://www.theverge.com/22435030/starlink-satellite-internet-spacex-review?scrolla=5eb6d68b7fedc32c19ef33b4
vs
https://www.theverge.com/22435030/starlink-satellite-internet-spacex-review

**Comment by necopinus** [comment]
More of these should be filtered in the current implementation. Open a new issue in https://github.com/The-Yak-Collective/onboarding_robot if I’ve missed some.
