### ISSUE TITLE
Migrate website to Gatsby

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#12]
https://www.gatsbyjs.org/

There's a lot of upcoming projects (like Vinay's "Yak Map") that are going to get more challenging to implement in Jekyll. We should migrate to a more flexible back-end before these needs become pressing.

Additionally, Netlify CMS supports React-based page preview templates, so moving to Gatsby will let editors using that instance see a more accurate representation of their edits than is currently possible.

**Comment by tilnow** [comment]
is this helpful? https://www.acuriousanimal.com/blog/2019/10/03/from-jekyll-to-gatsby
seems like we can tell gatsby how to convert the jekyll stuff. some things like member card formatting may be tricky, but simply a swap of variables. and then wrapping in js.
i think it can be done progressively:
1. make plain pages appear (includes setting up a netlify build)
2. create member page (no need to touch member cards)
3. use a default posts page
4. fix up headers and footers
5. add eye candy
6. add the automatic pull-in of data we already have
7. think about admin interface
8. start working on new stuff

**Comment by tilnow** [comment]
a different take on the matter some things are easy, but some, really not:
https://jaredpalmer.com/gatsby-vs-nextjs

**Comment by necopinus** [comment]
I mean, TBH I've had the best experiences with [Hugo](https://gohugo.io/), but it's not really suitable when you want to pull in multiple data sources, which is 100% the direction we're moving.

**Comment by necopinus** [comment]
I'm actually no longer convinced that this is where we want to go long-term, or even if such a migration is necessary at all (especially considering some of the work that's been done with Jekyll plugins). Closing for now.
