### ISSUE TITLE
Migrate Away from Using IFTTT to GitHub Actions

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#19]
This will require integrating RSS feeds, Twitter API calls, etc. into existing functions. The goal would be to pull everything from our member database at build time.

It's currently unclear how to handle scheduled rebuilds in this model.

**Comment by dahifi** [comment]
There background on the 'why' here? Something about IFTTT, or just using 3rd party service for this in general?

**Comment by necopinus** [comment]
In my experience there's real benefits to being as infrastructure independent/agnostic as possible. Right now I could imagine picking up the entire site and moving it to any random server with about a day's worth of work (the hardest part would be migrating the Netlify Function back to NodeJS, and that wouldn't be all that hard).

GitHub, Netlify, and in the background Amazon make things easier, but they're not "how do we function without this" critical.

Right now, the hooks in IFTTT _are_ critical, and only easily replaceable by migrating to some similar service like Zapier.

This ticket is my "note-to-self" that this kind of black-box dependency makes us brittle in a way I think should be fixed.

**Comment by tilnow** [comment]
using a  plugin (whose wrapping is netlify specific, but code is mostly reusable) we can read this information at build time. but that does not make sense to me. if somebody has a post or a twit or whatever, this is an event and should be treated when it happens.

so overall, what we seem to be building is a central coordinator (big brother?) that tracks members activities in all sorts of places, generates a repository, and then, when we build (or do some other automated action) we access that repository. do such tracking systems exist? i recall working with clients doing things like this 20 years ago. here is something similar: https://curator.io/blog/how-to-create-an-aggregator-website-and-why-you-should

**Comment by necopinus** [comment]
IFTTT is going to start requiring payment for more than three applets starting 10/7. I'll front the cost of this _temporarily_, but we should prioritize figuring out a new system.

GitHub Actions are promising for pulling in RSS feeds for the website, but we also need a method to push this data out to Twitter and Discord.

**Comment by tilnow** [comment]
i know that discord we can push using a "robot" that runs in github actions. the trick is - how often do we check. each time we have to start up the workflow. i assume twitter also has such an api.
i noticed somebody added zapier. that si just as good as ifttt

**Comment by necopinus** [comment]
IIRC, @vgururao had Zapier. Not sure if we're still using it for anything (I think it originally connected the YC Google Calendar to Discord, but now that's done using Carl?)... But it's also a paid service, and more expensive.

To give a sense of where we're at, we currently have 32 separate IFTTT applets:

1. 14 are used to push new posts from member RSS feeds into writings

2. 14 are used to push new posts from member RSS feeds into the YC Twitter (these mirror the 14 above)

3. 1 archives YakTalk newsletters

4. 1 pushes YakTalk newsletters to Twitter

5. 1 watches for new featured Yaks, and pushes them to Twitter

6. 1 forces the website to be rebuilt on a daily basis.

Thoughts (each corresponds to a point above):

1. My first pass system for pulling in member feeds did so at build time. Now that I understand GitHub Actions a bit better, I think this could be re-implemented using that system. The advantage with IFTTT is that we get the new member post in near "real time"; falling back to the old system in GitHub Actions means putting things on a timer. This is probably good enough for the website, but...

2. There's [a GitHub action to allow us to Tweet](https://github.com/marketplace/actions/twitter-action) the we could probably hook into the member post ingestion process. If we just push everything out when we get it, we run the risk of having 10 tweets in a row or something if it's been a while since we last ran. So maybe we should use the process for ingesting incoming posts to also create some directory of "future tweets", and then have a _different_ action come in and periodically tweet those out. Seems like we _may_ want this to live in a different repo, to prevent excessive rebuilds. We loose real-time tweeting, but maybe it's better to space content out a bit more regularly anyway?

3. YakTalk newsletters can be archived using the same internal process as we use to ingest member posts, as long as we don't care about this being "real time".

4. YakTalk newsletters can be pushed to Twitter using the same internal process as we use to push member posts... But it seems like timeliness is more important here?

5. Featured Yaks _could_ also use the same internal process to push things to Twitter, but timeliness seems _most_ important here. I'm almost inclined to have a special "pick a new featured member process" that both picks a new featured member and tweets that member out. If we do that, then we should move the logic for picking the featured member out of the Jekyll plugin (which has been restored in the `astonishing-stories` branch) and into this script. One possible advantage here: Since this is now its own process, we don't have to worry about consistency from build-to-build (we just run this bit once per day), so we can actually just use some built-in random number generator.

6. We can do this with a simple timed commit.

Doing all of this... Makes Netlify unnecessary? We've sacrificed timeliness, but have then moved all of the build logic into GitHub Actions. Feels like we should maybe just move back to using GitHub for hosting too. It turns out that [GitHub Actions can build and deploy Gatsby](https://github.com/marketplace/actions/gatsby-publish), and we can also [use GitHub Actions for more customized Jekyll builds](https://jekyllrb.com/docs/continuous-integration/github-actions/), so _right now_ we wouldn't loose anything. And it would significantly simplify our infrastructure.

**Comment by tilnow** [comment]
point by point (or actually thought by thought):
1. i am all for us having a cycle where we first read stuff (from feed, discord, roam), and then regenerate the website. i do not see why we need faster. if somebody is on the feed, they get it at once. and if not, what do another 24 hours mean to the? FWIW I have a blog I edit and am also subscribe to by feedburner and I get notified ~24 hours after posting
2. i think that si too figity. i prefer we connect ourselves to twitter API and tweet. we can do that in an action. i assume such tweeter robots don't have this limitation. if they do, I suggest we run some of these "robots" on a virtual host (like azure) and there we can easily space out tweets, etc.
3. agree.
4. I do not see why yaknewsletter cares about timeliness
5. since we do not feature somebody more than once a day and we plan (?) on rebuilding website once a day, I do not see the issue of timeliness. i feel that anything to do with website should be in the website, in script or whatever and not in a workflow
6. yes

seems like all the functions we use IFTTT can be easily done using a workflow

we can always take out netlify later. why rush? netlify also gives us  aCDN which may be better than github. and I really like the support for multiple branches, etc.

**Comment by necopinus** [comment]
(2) The GitHub Action Twitter poster looks to be just a light Go wrapper around the Twitter API. So I'm not sure there's much of a difference between that option and what you're describing. I'm mostly just concerned that we don't bunch up tweets; right now, we get spacing by virtue of the posts just not being at the same time. If we're running this all off of a timer, we just need to think through timing a bit, is all.

Point about Netlify's multi-branch support. No harm in leaving it in for now.

I'll start playing with all of this soon.

**Comment by tilnow** [comment]
does the twitter api not let us give a tweet time? where do I find the github API for twitter?

**Comment by vgururao** [comment]
Yes I have Zapier set up to post calendar events to twitter and #events on
discord. Do you want to get rid of that?

In general, I’m for sacrificing timeliness unless there is an actual
clock-time event deadline or something.

**Comment by tilnow** [comment]
@vgururao does Zapier cost anything? reminder - we want to 
1. reduce the number of tools we use 
2. move them away from individuals

**Comment by vgururao** [comment]
No, zapier is free at the level I’m using it (3 integrations, a handful of
triggered actions a week)

**Comment by tilnow** [comment]
so @necopinus, for now, maybe we should just move to zapier

**Comment by necopinus** [comment]
@vgururao How does Zapier count integrations?

IFTTT counts us as three integration:

- Webhook (one integration, even though we use a couple of different endpoints)
- RSS (one integration, even though we pull in 16 different feeds right now)
- Timer (used to trigger events on a schedule)
- Twitter (YC Twitter)

So, that might be too many. But maybe we could use Zapier for RSS-to-Twitter? I could spin up a single feed that would include featured yaks + member posts in a form more suitable for publishing directly. We might still get posts bunched up though, which makes me inclined to do some kind of system that spaces things out a bit more (especially if timeliness isn't a concern, which it sounds like it's not).

I'm being cheap with IFTTT, and am only paying $4/month, so it's not like this is a hardship. I just hadn't realized that they were going to limit the number of applets, so now I'm kinda pissed. Also, as Maier says, good to try to simplify our infrastructure a bit. :-)

**Comment by vgururao** [comment]
5 free integrations, 100 tasks/month, single-step integrations only, and 15
minute event trigger time. Paid gets you 5 minutes.

https://zapier.com/app/billing/plans

I'm using 3/5 and probably 25-30 tasks (each time the zap triggers, it
counts as a task)

**Comment by vgururao** [comment]
Also, we have budget to do a paid plan for YC, so we can do that... but I
guess we should do only one or the other if we're doing paid, not both? I
imagine the two have very similar functionalities?

How about you guys create a zapier account using the yc gmail, and explore
the capabilities.

**Comment by tilnow** [comment]
this seems to be hanging. what are we doing here? moving to zapier? paying ifttt?

**Comment by necopinus** [comment]
I haven't had the time to close the loop here yet. I laid down some money to keep IFTTT going before [my update above](#issuecomment-697015952), so this isn't a hair-on-fire situation.

My inclination is to re-implement things in GitHub actions, but it's worth exploring Zapier since we're already using it. I've got a set of Knack-related asks from Jenna + some work that needs to be done in the [`astonishing-stories`](https://github.com/The-Yak-Collective/yakcollective/tree/astonishing-stories) branch queued up ahead of this.

**Comment by necopinus** [comment]
Ask and ye shall receive: https://actionsflow.github.io/docs/

Between this and a simple timer workflow, we have a 100% replacement for IFTTT. (Need to look at how feasible it is to build a Google Calendar connector; if we can do that, it should be possible to also pull the YC stuff out of Zapier too.)

**Comment by tilnow** [comment]
awesome (though maybe a bit fidgety for the no-programming crowd)

since google calendar does webhooks: https://developers.google.com/calendar/v3/push and actionflows does webhooks: https://actionsflow.github.io/docs/webhook/ I expect the answer to be yes

**Comment by necopinus** [comment]
Updated title to reflect that ActionsFlow may not be the best solution (looks like a possibly dead project).

**Comment by necopinus** [comment]
This is as done as it's going to be. Twitter posting still requires IFTTT, but per discussion on Discord, if this breaks we don't really care now.

Everything else runs as a GitHub action now.
