### ISSUE TITLE
Replace Google Analytics?

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#20]
Some folks on Discord have expressed concern about Google Analytics + GDPR. How important is Google analytics for us? Is there a GDPR-compliant analytics service we can replace this with?

**Comment by dahifi** [comment]
Has some options to disable it that might warrant discussion: https://support.google.com/analytics/answer/9019185?hl=en

**Comment by necopinus** [comment]
We’re still not really using Google Analytics, and I’m not sure how well it fits within a web3 paradigm. Removed from `development`, and will be removed from `production` when we merge that set of changes in.
