### ISSUE TITLE
Add rotating slogans to Yak Collective pages

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#21]
Probably need to be inserted using JavaScript to get "true" slogan rotation, but we should also randomly assign defaults at build time.

We need a list of slogans. Some initial ideas:

https://discordapp.com/channels/692111190851059762/712112363566006322/719654392327962643

**Comment by tilnow** [comment]
tentatively assign to me please. see attached a proposed modification of footer.html to include random displaying of slogans from a file in the asset directory
[footer_rolling.html.txt](https://github.com/The-Yak-Collective/yakcollective/files/4898425/footer_rolling.html.txt)

**Comment by necopinus** [comment]
This is very cool @tilnow!

I can add this to the repo, but if you're comfortable with working with pull requests, it might be better to do a pull request against the v2.1 branch (which is what I'm currently working on). I _think_ that Netlify should generate a build against pull requests, though I haven't used that feature yet, so I'm not 100% how smooth the process is.

Right now, the v2.1 branch is building to https://optimistic-jennings-266cab.netlify.app/.

Some quick thoughts:

1. You should probably pull from `/assets/whatever_file.ext` instead of from GitHub.

2. In my ideal world, I imagine the slogan changing on page refresh, rather than every X seconds. So I think there's two parts to this: **(a)** A JavaScript snippet like the one you wrote that pulls a random slogan and sets it on page load, and **(b)** something that pulls random slogans and writes them into the `footer_slogan` div at build time, so that we have something "close enough" for folks who have JavaScript turned off.

3. As far as the slogans go... This was an idea that @vgururao originally came up with in the Discord `#infrastructure` channel. It might be good to check-in there and get ideas for slogans or suggestions for polling or some-such. I'm honestly not 100% sure what kinds of slogans @vgururao was thinking about.

**Comment by vgururao** [comment]
I can offer my collection of 100 consulting tips I was tweeting last year to start with. https://docs.google.com/document/d/1AlxBJJo1mzXeXKUis_vzTXnlkiLKYhi8MdiQaWs5LrA/edit

**Comment by tilnow** [comment]
Some of the consulting tips are too long to fit in the format i have now - a single line between "the yak collective" and the link buttons.
i'll see if i can fit it in the footer otherwsie

**Comment by vgururao** [comment]
Maybe just cherry-pick the ones that fit? It’s just a starter set after all that others can contribute to at the length you want. Not like they form a sequence with dependencies.

**Comment by tilnow** [comment]
the tips seem to be a very different flavor than the slogans i pulled from discord. some are just longer and some are much longer.

i am trying out now to add a menu item to show the tip of the day on a seperate page, so we can get a feeling for size.

**Comment by tilnow** [comment]
if you look [here](https://deploy-preview-36--optimistic-jennings-266cab.netlify.app/) (temporary preview) you can see what the tips look like on full page (using new menu item "daily tip") and also what slogans (i have ~8) look like in footer)

**Comment by tilnow** [comment]
as currently implemented, each page has its own random slogan, fixed at build time.

**Comment by necopinus** [comment]
Pull request #36 adds 99% of what we want here. All credit to @tilnow.

**Comment by necopinus** [comment]
Closed in ccdfbbe.
