### ISSUE TITLE
Move from Google Forms to Knack for the "Join" page

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#23]
- [ ] End on the (currently unused) "[welcome](https://github.com/The-Yak-Collective/yakcollective/blob/netlify-prod/welcome.md)" page (which should then link to the code of conduct)

- [ ] Catalogue people's skills at sign-up (with an opt-in). This should be used to populate some sort of member/skills database... Maybe built off of Vinay's "Yak Map" project? (This then begs the question of how we define who's a "member".)

**Comment by dahifi** [comment]
Not sure it helps, but Airtable might be slightly better option? Has webhooks that can be used to trigger Zapier actions.

**Comment by necopinus** [comment]
This should actually be a form that plugs into Knack. Thus depends on #71.

**Comment by necopinus** [comment]
Live in `production` now!
