### ISSUE TITLE
Add a "featured contributor" box to the homepage

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#27]
[Per](https://discord.com/channels/692111190851059762/704369362315772044/722144565141700769) @vgururao:

> Also, some more brainstorm cycles on promoting individuals would be helpful. I had a thought of adding a box to the front page showing "featured contributor" which just randomly showcases somebody from the directory (in future, in proportion to their yakcoins or contribution karma or something)

This will probably need to be done in JavaScript, though there should be some kind of (also random-ish) default defined at build-time (for folks who have JavaScript turned off).

For the moment, the obvious weighting is "contributor projects / total contributor projects", where "contributor projects" is a count of all (contributor, project) tuples for a given member, and "total contributor projects" is a count of all (contributor, project) tuples across all members.

**Comment by tilnow** [comment]
can i ask how many users have javascript turned off?
anyway, i can build such a box using javascript and/or at-build code, like i did with the slogans.

i think this highlights another issue - the infrastructure. stop me if i am going off the road please.

i do not think that right now we have a database with the information re contributions. i could extract it from the members .md files, but are these kept uptodate? or do we trust the users to?
right now it seems we are using three tools: roam, website & discord. roam has no api as yet (but may have one soon and there is a limited ability to scrape it). website has no real backend. is there a plan to add a database (like [faunaDB](https://www.netlify.com/blog/2019/09/10/announcing-the-faunadb-add-on-for-netlify/))? we can also implement one in github as a yaml file, but administration will not be fun.

**Comment by tilnow** [comment]
anyway, latest admin_improvements build: https://inspiring-villani-8898ca.netlify.app/ has it on home page. comments welcome.
right now no javascript because i used the jekyll include function. so it is fixed at build time. i assume we can add weighting too using jekyll

**Comment by tilnow** [comment]
i built a database on FaunaDB with an initial schema for member information and a suitable query, but according to [here](https://www.netlify.com/blog/2018/07/09/building-serverless-crud-apps-with-netlify-functions-faunadb/#2-set-up-faunadb) there is setup to be done in the netlify side. 

if you want me to try this out further - it is a serverless DB -  i think i need you to add the faunaDB-related steps to the build process and insert the  secret into the environment variable. everything else seems like i can do on the git side.

the downside of FaunaDB is that it uses javascript to read the DB from the page. maybe - i did not yet check - you can use the deploy-building event to execute at least the first time during build and after that the site will be static if no JS.

**Comment by necopinus** [comment]
For the purpose of this issue, "contributor" == "member", and for the purpose of anything on the website, "member" == "someone who is listed on a project page". So all this ticket is looking to do is to "feature" someone from the `members` collection on the homepage (first-pass is probably just as a member card).

All of the data we need is already in the `members` and `projects` collections -- `members` for the member data, and `projects` for a list of which projects they're associated with (for weighting). The JavaScript requirement is, as you observe, more-or-less what you already wrote for the slogans and tips.

The thing that maybe gets a little bit trickier here is that there's _a lot_ of member data that goes into a card. I think that one way to do this might be to pre-render member cards (not as full HTML, but just as a snippet), and then use the JavaScript to pull in whichever one we want to display right then. The current include can probably be more-or-less reused for this process.

FWIW, I think the right way to think of static websites is to remember that the filesystem _is_ a database of sorts. Each markdown/YAML file is a structured object, and all Jekyll is doing is performing some set of "queries" on that data that output final pages. We don't require dynamic content (outside of the sort of rotation you've already built), so any database that's "live" from the website user perspective is overkill / a potential security hole. (That said, treating the filesystem as a database in this way is inefficient / limiting. The main reason to move from Jekyll to Gatsby, which is what I'm trying to get my head around right now, is to allow for more efficient / flexible / diverse data structures moving forward.)

**Comment by tilnow** [comment]
take a look at the demo at https://inspiring-villani-8898ca.netlify.app/ where i show a card of a featured member & pls comment

even in gatsby, where is your database? that is why i tried out FaunaDB

**Comment by vgururao** [comment]
Oh nice! Since twitter is already integrated, could also tweet that member’s page with their twitter handle that day. In terms of layout, it’d be nice to have it more prominent: larger photo and box to the right of main feature blurb rather than below. But thus us a great mvp.

**Comment by tilnow** [comment]
i assume you only want to tweet once?
maybe we need an "always running" server (running in cloud) to do these such activities. what other things do you want to do daily?

to look into it, i need to know: where is twitter integrated?

**Comment by necopinus** [comment]
This is where things get super Rube Goldberg.

We have an IFTTT account that we use both to push content into GitHub (member posts) and Twitter. I _think_ all we should need to make this work is to generate an RSS feed the contains the member information we want to push to Twitter as its content. It should be pretty simple to adapt `writings/feed.xml` for this purpose.

**Comment by tilnow** [comment]
so:
should this issue be closed?
a new issue made for twitter?

**Comment by necopinus** [comment]
I think that there's two things still to do:

**(1)** Generate an RSS feed with the member info we want to push to Twitter. That will let me hook IFTTT into this so that (a short time) after the rebuild we'll get a "member of the day" Tweet.

**(2)** We don't want that feed to change _every_ time the site gets rebuilt, so we'll need to alter the algorithm that picks the featured contributor so that it only returns one unique result per day.

Thinking that maybe we should just strip out the JavaScript for the slogan/tip, and also set those up to regenerate only daily too. Forcing a daily rebuild isn't hard, but we can also probably do it by (ab)using any polling of Discord. (See my comment at the end of #32; if we always commit a random number --- or maybe a couple of different random numbers --- when Discord is polled, then we could use that to keep contributors, tips, etc. randomized while still only having a daily rebuild.)

**Comment by tilnow** [comment]
as to (1), we have a working example of building an RSS field, right?
as to (2), ok, will making the rando generator word on the day, be ok?
as to slogan/tip, i do not see/understand why any change is needed. also, what is the connection to discord? will look in #32 though. 

ok, now i understand. you want featured member to be updated even if there is no manual build. i do think javascript is better for this than forcing a rebuild. unless you want a daily rebuild on a regular bsis.

**Comment by tilnow** [comment]
[here](https://community.netlify.com/t/scheduling-builds-and-deploys-with-netlify/2563/5) is an idea for daily rebuild:

> Another cron alternative, if you want to build every hour for free, you can use IFTTT Date & Time 66 to trigger the webhook 

or this solution:

> Just to provide another solution to this, it is easy to use GitHub Actions 79 to schedule builds.
> 
> You only need to add 1 file to your GitHub repo: .github/workflows/main.yml
> 
> # .github/workflows/main.yml
> 
> name: Trigger Netlify Build
> on:
>   schedule:
>     # Run at 0815 daily
>     - cron: '15 8 * * *'
> jobs:
>   build:
>     name: Request Netlify Webhook
>     runs-on: ubuntu-latest
>     steps:
>       - name: Curl request
>         run: curl -X POST -d {} YOUR_BUILD_HOOK
> Replace YOUR_BUILD_HOOK with your Netlify Build hook url.
> You can use crontab.guru 39 to easily generate your cron schedule.
> A cron schedule of 0 */3 * * * would run every third hour, to answer the original question :point_up:
> 
> I wrote a blog post about this 150 and created an example GitHub repo 67 with this workflow if anyone is interested!

i don't have access to the IFTTT, but that should solve point #2, no?

**Comment by necopinus** [comment]
For an example of an RSS feed, look at `writings/feed.xml`. The biggest differences will be **(1)** data source and **(2)** that we'll only ever include a single item in the feed (the current "featured contributor").

As far as daily rebuilds go, we actually used to do this, so it's easy to set up. What I was getting at was that if we need to poll Discord daily, then we could use that build process to also kick off a rebuild by making some kind of "inconsequential" commit (even if there's not any new Discord info). And then I thought: "If we have that commit be a random number into a file, then we get one new random number every day and can use that to pick the slogan/tip/featured contributor." That has the advantage that every day we get a "truly" random (albeit it potentially correlated) value for these, but then subsequent rebuilds don't change anything (so we don't get, say, three different "featured contributors" in one day).

**Comment by tilnow** [comment]
i'll look into the feed, but not today.
i use the date itself as the "random number". we can random it a bit more, but i do not see need for storage

**Comment by necopinus** [comment]
Yeah, your right... I'm just making this too complicated.

As long as it's just the date, and doesn't include hours/minutes/seconds, we should be fine.

**Comment by tilnow** [comment]
are we setting up a daily build on ifttt? for now i am using seconds, simply because it helps me see changes during debugging. but we can change it when done. i will add it as a comment in code

**Comment by tilnow** [comment]
re feed for twitter. what exactly do we want to be on this feed. information? link to member page? something else?

**Comment by vgururao** [comment]
Member spotlight: <fname> <lname>: member-page link, <primary skill>,
follow <fname>: @handle

With .png member card showing photo?

**Comment by tilnow** [comment]
not final, but yes synchronized with index page and gets updated base don build date, not time.

https://inspiring-villani-8898ca.netlify.app/featured/feed.xml

it generates a feed with a link to the featured member's page.

instead, i can link to the current featured-member-page, at https://inspiring-villani-8898ca.netlify.app/featured/amifeatured/ which shows two alternative formats. we have no "special skill" entry.

comments?

**Comment by necopinus** [comment]
@tilnow: This looks like it's almost there. **(1)** I think we should just change the `<description>` to more closely match what @vgururao suggests. **(2)** I know it's not standard practice, but I think that we should maybe use the current date for the GUID. That should be okay because we only intend to update this once per day, and we don't want to potentially confuse whatever IFTTT's using as it's feed parser into thinking that it's seeing an old article (and thus doesn't need to trigger an event) if someone comes around again.

@vgururao (and @tilnow): The member page link will pull in the member's avatar as the page image, but Twitter will crop it down in a way we can't control. Folks headshots are _mostly_ centered, so this will often, but not always, work out okay. "Attaching" the member avatar to the feed as an `<enclosure>` would let me set up IFTTT to attach the image directly, which will bypass the cropping problem but won't give us a nice "Twitter card".

**Comment by tilnow** [comment]
1. i assume ifttt is using the publication date
2. i am still not sure i understand what the output looks like, as i lack a testbed to give me feedback. for example, i do not know what twitter actually shows - the link, the description, etc. any ideas on how to set it up? maybe you can setup ifttt to send a dm with the tweet to me? @maierfenster?

**Comment by necopinus** [comment]
So, IFTTT let's us construct an entry from information in the feed entry. It parses out the following content for each entry:

`EntryTitle` = `<title/>`
`EntryUrl` = `<link/>`
`EntryAuthor` = `<name/>` subfield of `<author/>`
`EntryContent` = `<content/>` or `<description/>`
`EntryImageUrl` = rather unreliably tries to identify an image (so, not the `<enclosure/>` that I'd originally thought)
`EntryPublished` = `<pubDate/>`

So, I think the right approach here is to abuse the interface: The content that we want to tweet should obviously go into `<content/>`, but I think then we should just make the member stub (`venkatesh-rao`, etc.) the `<author/>` and the member avatar URL the `<title/>`. I can construct the member URL in IFTTT using the stub, and inserting the full avatar URL as the title will let us use non-standardized avatar file names in the future.

The trick will be figuring out how much `<content/>` we can reliably generate in 280 characters (less, really, because the image URL will count against it).

**Comment by tilnow** [comment]
why not the url of the image on the website?
also, we can have a page which is the featured member and send a link to that (it need not be the same as the "standard" member page, but maybe it should

i think maybe ifttt might be degrading the experience, or maybe we need to define the url differently (so it includes the relevant unfurl information). twitter also does an unfurl and it can also highlight one or two fields. see https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
