### ISSUE TITLE
Improve admin interface (Netlify CMS)

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#38]
The admin interface is... not straight-forward.

**Comment by necopinus** [comment]
Initial comments by @tilnow:

> some comments. tell me if you prefer to have me enter them as issues in github. if so, where:
> 1. instructions for admin pages - i would not let users loose on admin without this.
> i have an idea. how about a new "collection" which is simply instructions for use and it would be first. look in "admin_test" branch for an example. i could not use a real help file because it looks like the preview does not give access to any content i changed/created in branch (#41)
> 2. number of users already at limit of usability. i guess it needs an alphabetic listing. also, do the names match the discord names? i think not. i think they should if discord is the "official" chat engine
> 3. no actual page for "yak wisdom project". i know there is a redirect, but redirect is basically to its child.
> 4. some items in assets are not "media" assets (e.g., css). can images be moved to a separate directory? maybe a sub-directory? looks like media_folder can be set to that.
> 5. what about posts? do they deserve management?
> 6. editing of tips, slogans does not show any slogans/tips to edit. maybe because no corresponding type (if one can exist) in _config.yml? now that i know a bit more about netlify, i think netlify does not have a widget suitable for yaml. the data files are in yaml so that jekyll can easily read them.
> 7. also, when i tried to save the first slogan, it gave an error (cannot get property...) when i edited that first slogan, it worked and saved. but it must be broken inside, because when i tried to go to workflow i got error of "Failed to load entry: TypeError: Cannot read property 'get' of undefined" and i cannot see any workflow entries.
> 8. when i try to enter a new member, and then i check in workflow, it says "invalid date" and does not let me publish. he lets me delete and lets me drag it to "in review". so cannot really test that.
> 
> hope this helps

I think most of these can be covered by better (_any_) documentation. Some of the errors should be investigated further and broken into their own tickets if it makes sense to do so.

**Comment by necopinus** [comment]
Breaking the above into todos:

- [x] Create built-in help document, improve inline help.

> 1. instructions for admin pages - i would not let users loose on admin without this.
> i have an idea. how about a new "collection" which is simply instructions for use and it would be first. look in "admin_test" branch for an example. i could not use a real help file because it looks like the preview does not give access to any content i changed/created in branch (#41)
>

**ok, did this, though the help file contents are not written yet. also, you see help as a file to be edited. not clear if i can avoid that**
> [...]
>
> 8. when i try to enter a new member, and then i check in workflow, it says "invalid date" and does not let me publish. he lets me delete and lets me drag it to "in review". so cannot really test that.

**now it works for me. but will it work for somebody else?**

- [ ] Figure out a better way to deal with long lists.

> 2. number of users already at limit of usability. i guess it needs an alphabetic listing. also, do the names match the discord names? i think not. i think they should if discord is the "official" chat engine

**not done. no idea how to yet. but there is a sort function, after all.*

- [x] Figure out if its feasible to edit `netlify.toml` in the admin interface.

**yes, for redirects. done**

> 3. no actual page for "yak wisdom project". i know there is a redirect, but redirect is basically to its child.

- [x] Move site assets out of `assets` folder, so that the only things in that folder are things that make sense to be accessible in the admin interface.


> 4. some items in assets are not "media" assets (e.g., css). can images be moved to a separate directory? maybe a sub-directory? looks like media_folder can be set to that.

**did the opposite - moved all images into an "img" subdirectory + edited all over the site**

- [x] Figure out why remaining editing errors are occurring, and fix them.

> 6. editing of tips, slogans does not show any slogans/tips to edit. maybe because no corresponding type (if one can exist) in _config.yml? now that i know a bit more about netlify, i think netlify does not have a widget suitable for yaml. the data files are in yaml so that jekyll can easily read them.
> 7. also, when i tried to save the first slogan, it gave an error (cannot get property...) when i edited that first slogan, it worked and saved. but it must be broken inside, because when i tried to go to workflow i got error of "Failed to load entry: TypeError: Cannot read property 'get' of undefined" and i cannot see any workflow entries.

**all these errors are fixed (when i use the site)**

**Comment by tilnow** [comment]
assign me please

**Comment by tilnow** [comment]
still open:
1. when i am not an authorized user, adding a new member, etc. generates an invalid date on the card in the workflow. but the data file itself does have a date - not clear if it matters in use

2. real help file contents and/or make file uneditable

**Comment by tilnow** [comment]
I think i am done here. pls approve of closing issue. BTW, you can see help file from website/help, no need to go into /admin

**Comment by necopinus** [comment]
Okay. Closing, though we'll need to clean up the branch and/or close out a few more projects before merging back into `netlify-prod`.

**Comment by tilnow** [comment]
what do i need to do so it is closed-closed? i do have other stuff happening on this branch, as you noticed.
* proposals (including a jekyll _plugin)
* probably a test member to be deleted. maybe also a test project
* featured member
