### ISSUE TITLE
Admin interface needs a preview of some kind

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#39]
I believe that it should be possible to write a preview widget once we've migrated the backend to Gatsby (#12).

**Comment by tilnow** [comment]
what do you mean by preview? when i allowed editor preview, it worked for .md pages.

**Comment by necopinus** [comment]
The idea is to have something a bit closer to a live preview of the page, rather than the more bare-bones "rich text editor" style "preview" we have right now. See:

https://www.netlifycms.org/docs/customization/

My thought was that this will probably be easier to implement once we've migrated to Gatsby, as Gatsby and NetlifyCMS are both based on React, and we may be able to use some/most of the work to rebuild the current theme in React to bootstrap this. That said, I'm basically just keyword-matching off of the linked page, and have given this more-or-less zero thought.

**Comment by tilnow** [comment]
i still don't understand what is missing in the preview. do you mean for pages in general or do you mean for specific types of data (which ones?)
i allowed preview on pages, pls tell me what i am missing here
https://inspiring-villani-8898ca.netlify.app/admin/#/collections/pages
and, you have a live-preview link on top

**Comment by necopinus** [comment]
Wow.

First, I didn't realize that Netlify CMS could get that far "out of the box".

The one place I'm nervous about this approach is the place where a "live preview" matters the most --- project pages. Those pages both have a lot of "content" that's actually determined by the frontmatter, and have things like hero background images and page colors that are tweakable. So having a preview for those pages that actually looks like the final rendered page is important if we don't want folks to have to go through a rebuild cycle when they're futzing with images, accent colors, etc.

I don't think the rendering has to be a 100% functional match, but the primary use-case I had in mind was moving in a direction where someone who was comfortable with the back-end didn't have to be involved for project roll-out.

**Comment by tilnow** [comment]
on the one hand, rebuild is "cheap". on the other hand, i would not want project-people to know anything about back end. maybe process should be that they put in info and some volunteer designer does the tweaks.

**Comment by tilnow** [comment]
or we can have a fixed format (like member changes) you cannot do anything about.

**Comment by tilnow** [comment]
i just ran a test. i added a new project. saved it. and on top line of page i indicated status as ready and then i did publish it now. that created a new build and the "preview" link lit up and i could see the new build with the project.

do we need more?
i.e., do we need non-administrators to have a preview as well?

**Comment by necopinus** [comment]
The idea is for non-admin people to be able to get a sense of what the page will look like (admins can just click on the link in GitHub). That means replicating things like rending markdown, inserting YAML properties in the right places, etc. One of the main reasons I was thinking about this was so that people could figure out accent color & hero image interactions themselves (accent colors that _look_ like they should work with a given hero background don't always, or sometimes require custom fading of the hero image).

Though, the side-by-side preview "feels" friendlier to me than the single-column design. So maybe it's worth having anyway, even if it doesn't really accomplish this goal?

**Comment by tilnow** [comment]
i am not sure the work is justified on this feature. new projects are not opened very often, are they?

**Comment by necopinus** [comment]
I think we're going to get quite a lot pretty soon... But I also think a lot's going to be in flux.

Two thoughts...

**(1)** I'm actually liking the current preview, in spite of its current limits. Is there a way to hide frontmatter, or perhaps render it in a more formatted way?

**(2)** Otherwise, let's just put a pin in this one. I don't want to close it out, as if we stick with an admin interface like this I think we should have a better preview... But a lot may change over the next, say, 8 weeks. Let's circle back to this after the v3.0 milestone.

**Comment by necopinus** [comment]
Dropping admin interface for now.
