### ISSUE TITLE
Randomize member page?

### ISSUE THREAD

**Issue by vgururao** [vgururao/yakcollective#69]
The member directory should be sortable by alphabetical order as currently shown, but that should not be the default view since it arbitrarily over-exposes some members and under-exposes others. Default sort order should be some flavor of random, so at each visit you see a different few people above the fold.  Other sort orders can be added (alphabetical, chronological by join date, project contribution karma...). Potentially integrate this idea with the "featured" member thing... where the featured member is also the random top member or something.

**Comment by tilnow** [comment]
is it enough/ok that the "random" order be fixed at build time?
is it acceptable if we just start member list at some random location and then go in order?

just asking, not yet sure how to implement this. though i think i would build a new list members_random from the existing list in members, in member-list.html

**Comment by vgururao** [comment]
Yes I think that will all work

**Comment by tilnow** [comment]
looks like jekyll has a built in filter called `sample` that does it. see also https://stackoverflow.com/questions/27179385/how-do-i-shuffle-the-order-of-an-array-in-jekyll

**Comment by necopinus** [comment]
In particular: https://stackoverflow.com/a/59833695

Cut-and-paste between lines 10 and 11 in `_layouts/member-list.html`, tweak some variable names, done.

...And I'm realizing that the entire approach with taking the modulo of the date that we've use elsewhere is _way_ too complicated; we should just be piping the array we want to randomize to `sample`, and then piping the output of that to `first` to strip the "array-ness" off of the resulting single-element array.

**Comment by tilnow** [comment]
the reason why i decided _not_ to change that is that i now generate the "featured_one" as a number. that number is part of the site data and can be used all over the place.

**Comment by tilnow** [comment]
i see you did not push (neither did i yet - lets decide tonight). here is my code:
`---
layout: minimal
---

<section>
	<header>
		<h1>Members</h1>
		{{ content }}
	</header>
#change starts here
{% assign num_members = site.members | size %}
{% assign membs = site.members | sample: num_members %}

	{% for member in membs %}
#and ends here
		{% if member.date <= site.time or site.future == true %}
			{% include member-card.html %}
		{% endif %}
	{% endfor %}
</section>
`

**Comment by tilnow** [comment]
pushed. works. see at https://inspiring-villani-8898ca.netlify.app/members/
