### ISSUE TITLE
create infrastructure map

### ISSUE THREAD

**Issue by tilnow** [vgururao/yakcollective#73]
like list in roam IT page, but also showing relations (what does what/data to what)  between components, so we can get a better "big picture" of how complex the setup is and how sensitive it is to outages.

should not be limited to only website.

**Comment by tilnow** [comment]
see demo system at [link](https://tilnow.github.io/docjs/index)

**Comment by necopinus** [comment]
"Final" map: https://github.com/The-Yak-Collective/infrastructure-map

All new development should be at that link.
