### ISSUE TITLE
re-orientation tool

### ISSUE THREAD

**Issue by tilnow** [vgururao/yakcollective#77]
**may include an email**:
I’d like fine-grained email alerts. People should have the ability to plug in with much narrower situation awareness. Needing to reorient to this whole discord and entire network’s activities is ridiculous to expect of anyone.
**may include some central depo**:
@grigori: I think we overestimate the complexity of this thing. There are just a handful of official projects + infrastructure currently in development. 
Regular status updates on these (in one place, I would keep it on Discord, subscribable via email) should help with orientation.

see more on #collaboration discussion of 9/9/2020 7am-ish

**Comment by necopinus** [comment]
Not a website issue _per se_.
