### ISSUE TITLE
Figure out a better way to share logins for Yak Collective infrastructure

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#8]
Right now, logins to selected services have been shared with a few folks individually. It would be good to have a central repository that folks use, so that if we need to update password info, that gets rolled out to everyone.

Options:

- KeeWeb
- 1Password
- LastPass
- BitWarden

What do current contributors use?

**Comment by dahifi** [comment]
I like Lastpass, sharing requires paid account. You can share without demasking passes (autofill).

**Comment by necopinus** [comment]
Things we need to define (generated mostly from today's #infrstructure call + some brief additional noodling on my end):

1. Threats
2. Assets
3. Risks (threats x assets)
4. Security roles
5. Asset groups (roles x risks x assets)
6. Guidelines for assigning people to roles
7. Options for storing/sharing credentials (see above)
    - Once this is decided, we'll need to implement it
8. Periodic review schedule (probably quarterly)

**Comment by necopinus** [comment]
We need to circle back to this during an #infrastructure channel chat. Removing milestone for now.

**Comment by tilnow** [comment]
discord can be used as a login option. maybe we should implement that. see some details [here](https://discord.com/developers/docs/topics/oauth2)

**Comment by necopinus** [comment]
Going to close this for now; this hasn't been as much of a problem as I initially feared, and more structured approaches will require more, well, organizational structure.
