### ISSUE TITLE
titlelinks.txt | can fix Amazon title scrape? eg [503 - Service Unavailable Error](https://www.amazon.co.uk/Concepts-Programming-Languages-Robert-Sebesta/dp/013394302X)

### ISSUE THREAD

**Issue by djinna** [vgururao/yakcollective#99]

**Comment by necopinus** [comment]
This is not easily fixable, as Amazon and other sites will throw up various bad pages when they detect bot-like activity (which we certainly are). The best we can do is hide these (which we now do).
